# Generated by Django 3.1.4 on 2021-07-07 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('votes', models.IntegerField(default=1)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmark', unique=True)),
                ('users_voted', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
